export const DELETE_CARD="DELETE_CARD";
export const ADD_CARD="ADD_CARD";
export const EDIT_CARD="EDIT_CARD";
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';